version: '2'

services:
  trust:
    image: indigoiam/trustanchors
    command: /bin/true

  iam-be1:
    container_name: iam-be1
    image: indigoiam/iam-login-service:latest

    environment:
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Dspring.profiles.active=h2-test
      IAM_HOST: iam1.local.io
      IAM_BASE_URL: https://iam1.local.io
      IAM_ISSUER: https://iam1.local.io
      IAM_USE_FORWARDED_HEADERS: "true"
      IAM_NOTIFICATION_DISABLE: "true"
      IAM_ORGANISATION_NAME: iam1

    volumes_from:
      - trust

  iam-be2:
    container_name: iam-be2
    image: indigoiam/iam-login-service:latest

    environment:
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Dspring.profiles.active=h2-test
      IAM_HOST: iam2.local.io
      IAM_BASE_URL: https://iam2.local.io
      IAM_ISSUER: https://iam2.local.io
      IAM_USE_FORWARDED_HEADERS: "true"
      IAM_NOTIFICATION_DISABLE: "true"
      IAM_ORGANISATION_NAME: iam2

    volumes_from:
      - trust

  esaco:
    container_name: esaco
    image: indigoiam/esaco:latest

    depends_on:
      - iam-be1
      - iam-be2

    dns_search: local.io

    environment:
      TZ: Europe/Rome
      ESACO_USE_FORWARD_HEADERS: "true"
      CLIENT_ADDRESS: esaco

    volumes:
      - /dev/urandom:/dev/random
      - ./application.yml:/esaco/config/application.yml

    volumes_from:
      - trust

  httpd:
    container_name: httpd
    build:
      context: httpd

    depends_on:
      - esaco

    environment:
      TZ: Europe/Rome

    volumes:
      - /dev/urandom:/dev/random

  iam-fe:
    container_name: iam-fe
    build:
      context: nginx

    depends_on:
      - iam-be1
      - iam-be2
      - esaco
      - httpd

    dns_search: local.io

    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam-fe
      NGINX_PORT: 443

    ports:
      - "443:443"
      - "80:80"

    volumes:
      - /dev/urandom:/dev/random

    networks:
      default:
        aliases:
          - iam-fe.local.io
          - iam1.local.io
          - iam2.local.io
          - esaco.local.io
          - apache.local.io
